
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { dbConfig } from "@/utils/dbConfig";
import Header from "./auth/sider/sider";
import { MdMenu } from "react-icons/md";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  async function RootLayout({

  

  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConfig()
  return (
    <html lang="en">
      <div className="md:flex gap-40 ">
      <div className=""><Header /></div>
      
      
      <body className={inter.className}></body>
      <div className="">{children}</div>
      </div>
      
    </html>
  );
}
